apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: DB
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: sqlsecretbysakthi    # echo -n "sqlsecretbysakthi" | base64
  MYSQL_USER: ghostblog                        # echo -n "ghostblog" | base64
  MYSQL_PASSWORD: sqlsecretbysakthi     # echo -n "sqlsecretbysakthi" | base64
