apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
type: Opaque
stringData:
  MYSQL_HOST: "your-db-host.example.com"
  MYSQL_DATABASE: "nextcloud"
  MYSQL_USER: "nextcloud_user"
  MYSQL_PASSWORD: "StrongDBPassword123"
