apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
type: Opaque
stringData:
  MYSQL_HOST: mysqlservice.db
  MYSQL_DATABASE: nextcloud
  MYSQL_USER: nextcloud_user
  MYSQL_PASSWORD: StrongDBPassword123
