apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secret
  namespace: portfolio
type: Opaque
data:
  MINIO_ACCESS_KEY: QnhJMms4OUQySUI1dk1XQ0VMWWw=       # Base64("BxI2k89D2IB5vMWCELYl")
  MINIO_SECRET_KEY: SURzSDBHV3dDT3pDbnFQeGJpdDNoR3c1SGVOdjIxaUdoaExxcDZTbw==  # Base64("IDsH0GWwCOzCnqPxbit3hGw5HeNv21iGhhLqp6So")

  MAIL_SENDER_ADD: c2FrdGhpc2FyYW4ua3NyQGdtYWlsLmNvbQ== # Base64("sakthisaran.ksr@gmail.com")
  MAIL_RECEIVER_ADD: c2FrdGhpc2FyYW5zc3M1NUBnbWFpbC5jb20= # Base64("sakthisaransss55@gmail.com")
  MAIL_PASSWORD: c3hubCBraWV6IHZlcmMgbWplZQ==             # Base64("sxnl kiez verc mjee")

  SECRET_KEY: OThmMmEzYzRiOGQ2ZTdmMWEyYjNjNGQ1ZTZmN2E4YjljMGQxZTJmM2E0YjZjNmQ3ZThmOWEwYjFjMmQzZTRmNWE= # Base64("9f2a3c4b8d6e7f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a")

  MONGO_URL: bW9uZ29idCtzdHI6Ly9zYWt0aGlzYXJhbjpxd2VydHl1aW9wMTIzQGNsdXN0ZXIwLjNwaWVmMjEubW9uZ29kYi5uZXQv # Base64("mongodb+srv://sakthisaran:qwertyuiop123@cluster0.3pief21.mongodb.net/")
