apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secret
  namespace: portfolio
type: Opaque
data:
  MINIO_ACCESS_KEY: BxI2k89D2IB5vMWCELYl     # Base64("BxI2k89D2IB5vMWCELYl")
  MINIO_SECRET_KEY: IDsH0GWwCOzCnqPxbit3hGw5HeNv21iGhhLqp6So  # Base64("IDsH0GWwCOzCnqPxbit3hGw5HeNv21iGhhLqp6So")

  MAIL_SENDER_ADD: sakthisaran.ksr@gmail.com # Base64("sakthisaran.ksr@gmail.com")
  MAIL_RECEIVER_ADD: sakthisaransss55@gmail.com # Base64("sakthisaransss55@gmail.com")
  MAIL_PASSWORD: sxnl kiez verc mjee            # Base64("sxnl kiez verc mjee")

  SECRET_KEY: 98f2a3c4b8d6e7f1a2b3c4d5e6f7a8b9c0d1e2f3a4b6c6d7e8f9a0b1c2d3e4f5a # Base64("9f2a3c4b8d6e7f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a")

  MONGO_URL: mongobt+str://sakthisaran:qwertyuiop123@cluster0.3pief21.mongodb.net/ # Base64("mongodb+srv://sakthisaran:qwertyuiop123@cluster0.3pief21.mongodb.net/")
