apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: DB
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        envFrom:
        - secretRef:
            name: mysql-secret
        resources:
          limits:
            memory: "700Mi"
            cpu: "800m"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysqldata
          mountPath: /var/lib/mysql
      volumes:
      - name: mysqldata
        persistentVolumeClaim:
          claimName: mysql-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysqlservice
  namespace: DB
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306