apiVersion: apps/v1
kind: Deployment
metadata:
  name: rediscache
  namespace: DB
spec:
  selector:
    matchLabels:
      app: rediscache
  template:
    metadata:
      labels:
        app: rediscache
    spec:
      containers:
      - name: rediscache
        image: redis:latest
        resources:
          limits:
            memory: "200Mi"
            cpu: "150m"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: rediscache
  namespace: DB
spec:
  selector:
    app: rediscache
  ports:
  - port: 6379
    targetPort: 6379