apiVersion: apps/v1
kind: Deployment
metadata:
  name: rediscache
  namespace: DB
spec:
  selector:
    matchLabels:
      app: rediscache
  template:
    metadata:
      labels:
        app: rediscache
    spec:
      containers:
      - name: rediscache
        image: redis:latest
        resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: DB
spec:
  selector:
    app: rediscache
  ports:
  - port: 6379
    targetPort: 6379