apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nextcloud-storage-class
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/appdata/nextcloud/config
    server: nfs.local
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
spec:
  capacity:
    storage: 2000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nextcloud-storage-class
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/appdata/nextcloud/data
    server: nfs.local
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config-pvc
  namespace: nextcloud
spec:
  storageClassName: nextcloud-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: nextcloud
spec:
  storageClassName: nextcloud-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi