apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-data-pv
  namespace: minio
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: minio-storage
  nfs:
    path: /var/nfs/minio
    server: nfs.local  
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-pvc
  namespace: minio
spec:
  storageClassName: minio-storage
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany