
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
  namespace: blog
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ghost-data
  nfs:
    path: /var/nfs/appdata/ghost
    server: nfs.local
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
  namespace: blog
  labels:
    app: ghost-pvc
spec:
  storageClassName: ghost-data
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany