
apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: n8n-storage-class
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/pg
    server: nfs.local  
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
  namespace: DB
  labels:
    app: n8n-pvc
spec:
  storageClassName: n8n-storage-class
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
