# ansible-playbook restore_ghost.yml -e "cert=/home/sakthi/.kube/config"

---
- name: Restore Ghost Kubernetes manifests from GitHub
  hosts: k8s-master
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Clone or update the Git repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dir }}"
        version: main   # or specify a tag/branch
        force: yes

    - name: Apply storage manifests
      community.kubernetes.k8s:
        kubeconfig: "{{ cert }}"
        state: present
        src: "{{ repo_dir }}/storage/"
      when: ansible_facts['os_family'] is defined

    - name: Apply secrets
      community.kubernetes.k8s:
        kubeconfig: "{{ cert }}"
        state: present
        src: "{{ repo_dir }}/secret/"

    - name: Apply configmaps
      community.kubernetes.k8s:
        kubeconfig: "{{ cert }}"
        state: present
        src: "{{ repo_dir }}/config/"

    - name: Apply resources (deployments, services, etc.)
      community.kubernetes.k8s:
        kubeconfig: "{{ cert }}"
        state: present
        src: "{{ repo_dir }}/resources/"
