# ansible-playbook restore_ghost.yml -e "cert=/home/sakthi/.kube/config resource=storage"

---
- name: Restore Ghost Kubernetes manifests from GitHub
  hosts: k8s-master
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Ensure git is installed
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: true

    - name: Clone or update the Git repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dir }}"
        version: main   # or specify a tag/branch
        force: true

    - name: Apply storage manifests
      kubernetes.core.k8s:
        kubeconfig: "{{ cert }}"
        state: present
        src: "{{ repo_dir }}/storage/"
      when:
        - ansible_facts['os_family'] is defined
        - resource == "storage"

    - name: Apply secrets
      kubernetes.core.k8s:
        kubeconfig: "{{ cert }}"
        state: present
        src: "{{ repo_dir }}/secret/"
      when:
        - ansible_facts['os_family'] is defined
        - resource == "secrets"

    - name: Apply configmaps
      kubernetes.core.k8s:
        kubeconfig: "{{ cert }}"
        state: present
        src: "{{ repo_dir }}/config/"
      when:
        - ansible_facts['os_family'] is defined
        - resource == "configmaps"

    - name: Apply resources (deployments, services, etc.)
      kubernetes.core.k8s:
        kubeconfig: "{{ cert }}"
        state: present
        src: "{{ repo_dir }}/resources/"
      when:
        - ansible_facts['os_family'] is defined
        - resource == "resources"
    - name: Apply ingress resources
      kubernetes.core.k8s:
        kubeconfig: "{{ cert }}"
        state: present
        src: "{{ repo_dir }}/ingress/"
      when:
        - ansible_facts['os_family'] is defined
        - resource == "ingress"

    - name: Cleanup cloned repository
      ansible.builtin.file:
        path: "{{ repo_dir }}"
        state: absent
      when: skip_cleanup is defined