- hosts: k8s-cluster
  become: yes
  tasks:
    - name: Install snapd (required for MicroK8s)
      apt:
        name: snapd
        state: present
        update_cache: yes

    - name: Install MicroK8s
      snap:
        name: microk8s
        classic: yes
        state: present

    - name: Add user to microk8s group
      user:
        name: "{{ ansible_user }}"
        groups: microk8s
        append: yes

    - name: Ensure microk8s is ready
      command: microk8s status --wait-ready

    - name: Enable essential MicroK8s add-ons
      command: >
        microk8s enable dns storage metallb:192.168.1.240-192.168.1.250 metrics-server
        dashboard ingress rbac
      args:
        warn: false

- hosts: k8s-master
  become: yes
  tasks:
    - name: Generate join token for workers
      command: microk8s add-node
      register: join_command

    - name: Save join command for workers
      set_fact:
        microk8s_join: "{{ join_command.stdout_lines[-1] }}"

- hosts: k8s-workers
  become: yes
  tasks:
    - name: Join MicroK8s cluster
      command: "{{ hostvars['k8s-master']['microk8s_join'] }}"
