
- hosts: k8s-master
  become: yes
  tasks:
    - name: Apply storage manifests
      community.kubernetes.k8s:
        kubeconfig: /path/to/kubeconfig
        state: present
        src: /path/to/kube/storage/

    - name: Apply secrets
      community.kubernetes.k8s:
        kubeconfig: /path/to/kubeconfig
        state: present
        src: /path/to/kube/secret/

    - name: Apply configmaps
      community.kubernetes.k8s:
        kubeconfig: /path/to/kubeconfig
        state: present
        src: /path/to/kube/config/

    - name: Apply other resources
      community.kubernetes.k8s:
        kubeconfig: /path/to/kubeconfig
        state: present
        src: /path/to/kube/resources/