apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-api
  namespace: portfolio
spec:
  # replicaset: 1
  template:
    metadata:
      labels:
        app: portfolio-api
    spec:
      containers:
      - name: portfolio-api
        image: sakthisaran/portfolio_api_2.0:latest
        env:

        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-apiservice
spec:
  type: LoadBalancer
  selector:
    app: portfolio-api
  ports:
  - port: 80
    targetPort: 80