apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgressql
  namespace: DB
spec:
  selector:
    matchLabels:
      app: postgressql
  template:
    metadata:
      labels:
        app: postgressql
    spec:
      containers:
      - name: postgressql
        image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
        envFrom:
        - secretRef:
            name: postgres-secret
        resources:
          limits:
            memory: "800Mi"
            cpu: "300m"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: postgres-sql-pvc
      securityContext:
        runAsUser: 999 
        runAsGroup: 999

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-sql-service
  namespace: DB
spec:
  selector:
    app: postgressql
  ports:
  - port: 5432
    targetPort: 5432
